name: PurpurPvP
version: '1.0'
main: com.usainsrht.purpurpvp.PurpurPvP
loader: com.usainsrht.purpurpvp.PurpurPvPLoader
bootstrapper: com.usainsrht.purpurpvp.PurpurPvPBootstrap
api-version: '26.2'
description: A comprehensive PvP plugin with duels, kits, ranked, and matchmaking.
authors:
  - usainsrht

permissions:
  purpurpvp.duel:
    description: Allows using /duel
    default: true
  purpurpvp.queue:
    description: Allows using /queue
    default: true
  purpurpvp.admin:
    description: Access to admin commands
    default: op
  purpurpvp.admin.sign:
    description: Allows creating PvP room signs
    default: op

